{"name": "Login In the Website", "status": "failed", "statusDetails": {"message": "Failure occurred and exit-on-failure mode is in use."}, "start": 1666105276852, "stop": 1666105276853, "uuid": "e5a58f61-5a23-43c8-869d-353ea3b7bd7e", "historyId": "4816dc0642208f48dff3bd67c2cd6955", "fullName": "TestCases.LoginTest.Login In the Website", "labels": [{"name": "suite", "value": "TestCases"}, {"name": "subSuite", "value": "LoginTest"}, {"name": "framework", "value": "robotframework"}, {"name": "language", "value": "cpython3"}, {"name": "host", "value": "MSDT081"}, {"name": "thread", "value": "default-5538b50a-eac0-4cc2-8db2-64e5dbdc92a8"}, {"name": "tag", "value": "robot:exit"}, {"name": "tag", "value": "robot:exit"}]}